language: java
deploy:
	provider: heroku
	api_key:
		secure: 
qANZp7AMsBMPYVKxTfslvRXTbZZ7uTOHYaFJlrWjfWyxcMg+Di1EmO7Qn77bOrftRxaQ7dKzpghOj6hPqlAFJsRovwpMKHtuP5r0K9HsQUX36aEYd07DHBL9xJ0opCjQpfswW1VNWRj/D0YpczTNUWu5PWGpksna4wsqT8nToyrNSwlReZKBnqiQPhtJKP8TG4rr43RCiyG5ZoGStux4EKPwzN3VP8eOY9QfDOTgG4cUZmuQvy+NmcAXKweP24QfrCwzbfpHA+tA0HO3yixYRwTdjqp77gNISAeZbb/6rf/h9tVpCIPorM7c64MU8/gJt1Dr5uor1BsDQlxcNrBpUMBDD+mHKCoC6hS4MFkVJ0SMM98NSA5EAhB2P8KMCMwmDQSAB03+SPSq7F7Ry03pZb5XJ4ptEC7y3okLz7h+/kGZDli6GsrRRyJXOzotc3hqItAsWI8SFA/6OnwuKgpqnr87EVHFHUwa8kQdGzJhD7mXYjbb4ur5v0GtPjoZ0EAz/uk4MI+jOCgR+I8ZxEX9G8H451ONnrLRqNUGcV0v7bEN32esBslHwopag7hkQNY/Y0LXYEhP9F6EVBTAKoJxKWMSTgJbgWKAm+8uY4JxwBus27aqh4JnS9zjt7ZO+e5eEHShN5PVElYFKgjTBSR1rLeiEeg2Efb8lCWm2U/dLxQ=
